# Version of Docker-compose
version: '3.9'
services:
  # Add the node-js service
  node:
  # Location to the node.js dockerfile
    build: 
      context: ./devtool_backend
        # Name of the dockerfile
      dockerfile: Dockerfile
      image: tathus/img_backend:lastest
    container_name: backend
    ports:
       # Host port:Container port
      - '4000:4000'
   
  react:
  # Location to the react.js dockerfile
    build: 
      context: ./devtool_frontend
        # Name of the dockerfile
      dockerfile: Dockerfile
      image: tathus/img_frontend:lastest
    container_name: frontend
    ports:
     # Host port:Container port
      - '3000:3000'
    stdin_open: true
